config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'persons/profile'

  constraints host: /^www\./i do
    get ':any',
        to: redirect {|p, req| "#{req.protocol}#{req.host_with_port[4..-1]}/#{p[:any]}" },
        any: /.*/
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'feedback' => 'feedback#new', as: :feedback
  post 'feedback' => 'feedback#create'

  resources :news, only: [:index, :show]

  get '*page_path' => 'pages#show', as: :page

  root 'home#index'
  get 'persons/profile', as: 'user_root'

end

app/models/news.rb
class News < ActiveRecord::Base

  acts_as_seo_carrier
  acts_as_static_files_holder

  mount_uploader :preview, NewsPreviewUploader

  validates :title, :published_at, presence: true
  validates :slug, uniqueness: true

  after_initialize :set_defaults
  before_validation :prepare_slug

  scope :visibles, -> { where("news.published_at < ?", Time.now).
                        where(hided: false) }
  scope :ordered, -> { order(published_at: :desc, id: :desc) }

  def display_name; title end

  def seo_image; preview.url end

  private

  def set_defaults
    self.published_at = Time.now if self.published_at.nil?
  end

  def prepare_slug
    self.slug = UrlStringPreparator.slug self.slug, self.title
  end

end

app/controllers/news_controller.rb
class NewsController < FrontendController
  def index
    @seo_carrier ||= OpenStruct.new(title: I18n.t('defaults.page_titles.news'))
    @news_list = News.visibles.ordered.page params[:page]
    respond_to do |format|
      format.html
    end
  end

  def show
    @news = News.find_by_slug! params[:id] #, conditions: ['hided = ?', false]
    @seo_carrier = @news
    respond_to do |format|
      format.html
    end
  end
end

app/views/news/index.html.slim
section.holder
  article.content
    h1 = @seo_carrier.title

    - if @news_list.any?
      ul
        - @news_list.each do |news|
          li
            .h3 = link_to news.title, news_path(news.slug)
            .published_at = I18n.l news.published_at, format: :long
            p
              - unless news.preview.blank?
                = image_tag news.preview.url, class: 'pull-left', style: 'margin: 0 1em 1em 0'
              = news.intro
      = paginate @news_list
    - else
      p = t 'defaults.empty_collections.news'

app/views/news/show.html.slim
section.holder
  article.content
    h1 = @news.title
    .published_at: em = I18n.l @news.published_at, format: :long
    == @news.body