config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'persons/profile'

  constraints host: /^www\./i do
    get ':any',
        to: redirect {|p, req| "#{req.protocol}#{req.host_with_port[4..-1]}/#{p[:any]}" },
        any: /.*/
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'feedback' => 'feedback#new', as: :feedback
  post 'feedback' => 'feedback#create'

  resources :news, only: [:index, :show]

  get '*page_path' => 'pages#show', as: :page

  root 'home#index'
  get 'persons/profile', as: 'user_root'

end

app/models/feedback.rb
class Feedback
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :message

  validates :name, :email, presence: true
  validates :email, email: true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < FrontendController
  def new
    @seo_carrier ||= OpenStruct.new(title: I18n.t('defaults.page_titles.feedback'))
    @feedback = Feedback.new
  end

  def create
    @seo_carrier ||= OpenStruct.new(title: I18n.t('defaults.page_titles.feedback'))
    @feedback = Feedback.new(feedback_params)

    # robots detections with fake surname field
    robot_detected = params[:feedback] && params[:feedback][:surname].present?

    respond_to do |format|
      if @feedback.valid?
        # flag to show success message instead feedback form in the view
        @success_feedback = true

        # Can be raised error during email delivery, as example:
        # Net::SMTPFatalError (550 Message was not accepted -- invalid mailbox.
        # Local mailbox nefedova.polina@list.ru is unavailable: user is terminated)
        # use begin..rescue..end if you need continue execution any way
        FeedbackMailer.feedback_message(@feedback).deliver unless robot_detected

        format.html { render action: 'new' }
        format.json { render json: @feedback, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :message)
  end
end

app/views/feedback/new.html.slim
section.holder
  h1.h1-title = @seo_carrier.title

  - if @success_feedback
    p = t 'feedback.success'

  - else
    = form_for @feedback, method: :post, url: feedback_path do |f|
      .f-field.f-field-required
        .f-line = f.label :name, t('feedback.name')
        .f-line = f.text_field :name

      / Fake field — the trap for robots
      /   display:none rule better move to css file
      /   html code must be similar to other fields — it's important
      .f-field.f-field-required style="display:none"
        .f-line
          label for="feedback_surname" Surname
        .f-line
          input type="text" name="feedback[surname]" id="feedback_surname"

      .f-field.f-field-required
        .f-line = f.label :email, t('feedback.email')
        .f-line = f.email_field :email

      .f-field.f-field-required
        .f-line = f.label :message, t('feedback.message')
        .f-line = f.text_area :message

      .f-field.f-submit
        = f.submit t('feedback.submit')